spring.application.name=musty-process-payment
server.port=8083

# ====================
# Kafka Configuration
# ====================
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# ======================
# Postgres Configuration
# ======================
spring.postgres.datasource.jdbc-url=${SPRING_POSTGRES_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/payments_db}
spring.postgres.datasource.username=${SPRING_POSTGRES_DATASOURCE_USERNAME:decagon}
spring.postgres.datasource.password=${SPRING_POSTGRES_DATASOURCE_PASSWORD:papi}
spring.postgres.jpa.hibernate.ddl-auto=update

#spring.jpa.hibernate.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.group.tomcat=org.apache.catalina, org.apache.coyote, org.apache.tomcat
logging.level.root=${LOGGING_LEVEL:info}
logging.level.org.springframework.web=${LOGGING_LEVEL:info}
logging.level.org.apache.camel=${LOGGING_LEVEL:info}
logging.level.tomcat=${LOGGING_LEVEL:info}
logging.pattern.console="%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){yellow} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=info, health, metrics
management.server.port=8083

camel.springboot.jmx-enabled=false
camel.springboot.main-run-controller=true
camel.springboot.name=payment-service

camel.servlet.mapping.enabled=true
camel.servlet.mapping.context-path=/webhooks/*
camel.servlet.mapping.servlet-name=PaymentWebhookServlet

paystack.secret-key=sk_test_bc0a751fa45d6e182ca8c152679744b44fd361bc
app.webhook-url=/webhooks/paystack
app.base-url=${APP_BASE_URL:http://localhost:8083}

