spring.application.name=musty-inventory-service
server.port=8081

# ====================
# Kafka Configuration
# ====================
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# =======================
# MySQL (Product Catalog)
# =======================
spring.mysql.datasource.jdbc-url=${SPRING_MYSQL_DATASOURCE_JDBC_URL:jdbc:mysql://127.0.0.1:3306/inventory_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.mysql.datasource.username=${SPRING_MYSQL_DATASOURCE_USERNAME:root}
spring.mysql.datasource.password=${SPRING_MYSQL_DATASOURCE_PASSWORD:papimaciano}
spring.mysql.datasource.hikari.maximum-pool-size=10

camel.springboot.jmx-enabled=false
camel.springboot.main-run-controller=true
camel.springboot.name=inventory-service

logging.group.tomcat=org.apache.catalina, org.apache.coyote, org.apache.tomcat
logging.level.root=${LOGGING_LEVEL:info}
logging.level.org.springframework.web=${LOGGING_LEVEL:info}
logging.level.org.apache.camel=${LOGGING_LEVEL:info}
logging.level.tomcat=${LOGGING_LEVEL:info}
logging.level.org.apache.camel.component.sql=DEBUG
logging.pattern.console="%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){yellow} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=info, health, metrics
management.server.port=8081
