spring.application.name=musty-notification-service
server.port=8084

# ====================
# Kafka Configuration
# ====================
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# =====================
# MongoDB Configuration
# =====================
spring.data.mongodb.uri=mongodb+srv://ilemonamustapha_db_user:UhEtvIBacDmduOPP@musty-cluster.b8cyyjp.mongodb.net/notifications?retryWrites=true&w=majority&appName=Musty-cluster

logging.group.tomcat=org.apache.catalina, org.apache.coyote, org.apache.tomcat
logging.level.root=${LOGGING_LEVEL:info}
logging.level.org.springframework.web=${LOGGING_LEVEL:info}
logging.level.org.apache.camel=${LOGGING_LEVEL:info}
logging.level.tomcat=${LOGGING_LEVEL:info}
logging.pattern.console="%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){yellow} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=info, health, metrics
management.server.port=8084

camel.springboot.jmx-enabled=false
camel.springboot.main-run-controller=true
camel.springboot.name=notification-camel-service

# camel.component.jetty removed: Jetty is not a runtime dependency in this service
#camel.component.jetty.use-global-ssl-context-parameters=true
