version: "3.8"
services:
  # --- MICROSERVICES ---
  order-service:
    container_name: order-service
    build:
      context: ./musty-create-order
      dockerfile: Dockerfile
    ports:
      - "9086:8086"
    depends_on:
      inventory-db:
        condition: service_healthy
      order-db:
        condition: service_started
      kafka:
        condition: service_started
    networks:
      - saga-net
    environment:
      - SPRING_POSTGRES_DATASOURCE_JDBC_URL=jdbc:postgresql://order-db:5432/orders_db
      - SPRING_POSTGRES_DATASOURCE_USERNAME=saga
      - SPRING_POSTGRES_DATASOURCE_PASSWORD=papi
      - SPRING_MYSQL_DATASOURCE_JDBC_URL=jdbc:mysql://inventory-db:3306/db_create_order?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_MYSQL_DATASOURCE_PASSWORD=papimaciano
      - SPRING_MYSQL_DATASOURCE_USERNAME=root
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    restart: on-failure

  payment-service:
    container_name: payment-service
    build:
      context: ./musty-process-payment
      dockerfile: Dockerfile
    ports:
      - "9087:8087"
    depends_on:
      - payment-db
      - kafka
    networks:
      - saga-net
    environment:
      - SPRING_POSTGRES_DATASOURCE_JDBC_URL=jdbc:postgresql://payment-db:5432/payments_db
      - SPRING_POSTGRES_DATASOURCE_USERNAME=saga
      - SPRING_POSTGRES_DATASOURCE_PASSWORD=papi
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    restart: on-failure

  notification-service:
    container_name: notification-service
    build:
      context: ./musty-notification-service
      dockerfile: Dockerfile
    ports:
      - "9088:8088"
    depends_on:
      - kafka
    networks:
      - saga-net
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://ilemonamustapha_db_user:UhEtvIBacDmduOPP@musty-cluster.b8cyyjp.mongodb.net/notifications?retryWrites=true&w=majority
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    restart: on-failure

# --- DATABASES ---
  order-db:
    container_name: order-db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=saga
      - POSTGRES_PASSWORD=papi
      - POSTGRES_DB=orders_db
    networks:
      - saga-net
    ports:
      - "5433:5432"
    volumes:
      - order_data:/var/lib/postgresql/data

  inventory-db:
    container_name: inventory-db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=papimaciano
      - MYSQL_DATABASE=db_create_order
    networks:
      - saga-net
    ports:
      - "3307:3306"
    volumes:
      - inventory_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  payment-db:
    container_name: payment_db
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=saga
      - POSTGRES_PASSWORD=papi
      - POSTGRES_DB=payments_db
    networks:
      - saga-net
    ports:
      - "5434:5432"
    volumes:
      - payment_data:/var/lib/postgresql/data

  # --- INFRASTRUCTURE (KAFKA KRAFT) ---
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    networks:
      - saga-net
    ports:
      - "29092:29092"
    environment:
      # KRaft settings
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # Ensure a cluster ID is set
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk
    volumes:
      - kafka_data:/var/lib/kafka/data
networks:
  saga-net:
    driver: bridge

volumes:
  order_data:
  inventory_data:
  payment_data:
  kafka_data:
