spring.application.name=musty-create-order

server.servlet.context-path=/order
server.port=8086

#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=${SERVERSTORE_PATH:classpath:zenz-mw-keystore.jks}
#server.ssl.key-store-password=${SERVERSTORE_PASSWORD:zenz-mw-keystore12}
#server.ssl.key-alias=zenz-mw-keystore
#security.require-ssl=true

camel.component.http.connect-timeout=1000
camel.component.http.connection-request-timeout=10000
camel.component.http.connections-per-route=300
camel.component.http.max-total-connections=2600
camel.rest.component=servlet
camel.rest.port=${server.port:8080}
camel.servlet.mapping.context-path=${API_PATH_VERSION:/api/v1/*}
camel.servlet.mapping.enabled=true
camel.servlet.mapping.servlet-name=CamelServlet
camel.springboot.jmx-enabled=true
camel.springboot.main-run-controller=true
camel.springboot.name=ng-check-product-existence
swagger.api.enableCors=true
swagger.api.path=/api
swagger.api-docs.path=/api-docs
swagger.api-docs.version=1.0.0

# =======================
# Postgres Configuration
# =======================
spring.postgres.datasource.url=${SPRING_DATASOURCE_ORDER_URL:jdbc:postgresql://order-db:5432/orders_db)
#spring.postgres.datasource.username=postgres
#spring.datasource.password=papi
#spring.postgres.jpa.hibernate.ddl-auto=update
#spring.postgres.database.driverClassName=org.postgresql.Driver
#spring.postgres.jpa.hibernate.show-sql=true
#spring.postgres.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.postgres.datasource.hikari.maximum-pool-size=10

# ===========================
# MySQL Configuration
# ===========================
spring.mysql.datasource.url=${SPRING_DATASOURCE_INVENTORY_URL:jdbc:mysql://inventory-db:3306/db_create_order}
#spring.mysql.database.driverClassName=com.mysql.cj.jdbc.Driver
spring.mysql.datasource.username=root
spring.mysql.datasource.password=papimaciano


# ===========================
# kafka Configuration
# ===========================
camel.component.kafka.brokers=${CAMEL_COMPONENT_KAFKA_BROKERS:kafka:9092}

logging.group.tomcat=org.apache.catalina, org.apache.coyote, org.apache.tomcat
logging.level.root=${LOGGING_LEVEL:info}
logging.level.org.springframework.web=${LOGGING_LEVEL:info}
logging.level.org.apache.camel.component.http=DEBUG
logging.level.org.apache.camel=${LOGGING_LEVEL:info}
logging.level.tomcat=${LOGGING_LEVEL:info}
logging.level.com.zenith=${LOGGING_LEVEL:info}
logging.pattern.console="%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){yellow} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

logging.level.org.springframework.jdbc.core=DEBUG
logging.level.org.apache.camel.component.sql=DEBUG

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=info, health, metrics
management.security.enabled=false
management.server.port=8086

#MultiParts Config
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

camel.component.jetty.use-global-ssl-context-parameters=true

atomic.protocol=${ATOMIC_PROTOCOL:smtp}
atomic.host=${ATOMIC_HOST:smtp.sendgrid.net}
atomic.username=${ATOMIC_USERNAME:apikey}
atomic.port=${ATOMIC_PORT:25}
atomic.uri=${atomic.protocol}://${atomic.host}:${atomic.port}?username=${atomic.username}&password=

ehf.host=${EHF_HOST:localhost}
ehf.method=POST
ehf.path=/api/ehf/fetchKeys
ehf.port=${EHF_PORT:8081}
ehf.protocol=${EHF_PROTOCOL:http}
ehf.uri=${ehf.protocol}://${ehf.host}:${ehf.port}${ehf.path}${ehf.uri-params}
ehf.uri-params=?bridgeEndpoint=true&httpMethod=${ehf.method}&throwExceptionOnFailure=true

vault-connector.host=${VAULT_HOST:localhost}
vault-connector.method=GET
vault-connector.path=/api/credentials/
vault-connector.port=${VAULT_PORT:8083}
vault-connector.protocol=${VAULT_PROTOCOL:http}
vault-connector.uri=${vault-connector.protocol}://${vault-connector.host}:${vault-connector.port}${vault-connector.path}
vault-connector.uri-params=?bridgeEndpoint=true&httpMethod=${vault-connector.method}&throwExceptionOnFailure=false




